general:
  debug: false
  plugin-stats-opt-out: false
ach:
  database:
    type: file
    host: localhost
    username: Beardstats
    password: changeme
    database: stats
  msg:
    person: "Achievement Unlocked: <ACH>"
    broadcast: "<PLAYER> Unlocked: <ACH>"
    ach: "Visit our website to view all your achievements."
    send: "BROADCAST" 